### ISSUE TITLE
Add context-specific escaper helpers

### ISSUE THREAD

**Issue by weierophinney** [zendframework/zend-expressive-platesrenderer#21]
This component should include an extension with the following context-specific escaping mechanisms from zend-escaper:

- `escapeHtml()`
- `escapeHtmlAttr()`
- `escapeJs()`
- `escapeCss()`
- `escapeUrl()`

Adding these would be a value-add for those using Plates with Expressive, and provide added security features for template authors.

**Comment by harikt** [comment]
Please close this issue for its implemented in #22 .

Thank you.
