### ISSUE TITLE
Make UrlExtension optional

### ISSUE THREAD

**Issue by acelaya** [zendframework/zend-expressive-platesrenderer#24]
I have recently migrated two expressive projects from twig to plates, and in both of them I have faced the same problem.

The twigrenderer package includes a set of factories that register a twig extension enabling access to the `UrlHelper` and the `ServerUrlHelper`, from the helpers package, but only if both of them are registered in the container.

On the other hand, the platesrenderer package factories force you to register them, otherwise an exception is thrown.

I was not using them in those projects, and I have been forced to install the helpers package and register both services.

Would it make sense to make it optional as in the twigrenderer?

I could provide a PR if you are ok with this idea.

**Comment by weierophinney** [comment]
Absolutely - go for it!

**Comment by acelaya** [comment]
Create pull request #25
