### ISSUE TITLE
Proposal to Enable Plates Asset Extension

### ISSUE THREAD

**Issue by stormwild** [zendframework/zend-expressive-platesrenderer#3]
Proposal to refactor PlatesRendererFactory to enable [asset extension](http://platesphp.com/extensions/asset/).

``` php
use League\Plates\Extension as PlatesExtension;

// Create the engine instance:
$engine = new PlatesEngine();

// Enable asset extension
$engine->loadExtension(new PlatesExtension\Asset($config['paths']['assets']));
```

This will allow plates-layout.phtml in zend-expressive-skeleton to reference assets similar to:

``` php
<img src="<?=$this->asset('zf-logo.png')?>" alt="Zend Expressive" />
```

Where the assets path is configured in templates.global as:

``` php
    'templates' => [
        'extension' => 'phtml',
        'paths' => [
            'assets' => 'public',
            'app'    => ['templates/app'],
            'layout' => ['templates/layout'],
            'error'  => ['templates/error'],
```

**Comment by mwillbanks** [comment]
I'm not certain that this is really the place to put it, it's certainly already possible by using a container and the manual instantiation vs. the factory instantiation.  The problem you will start to run into is where does that stop for hooking everything?

Basically the factories should be mostly interchangeable and adding implementation logic on each one can lead to highly customized factories that ultimately do several things that are just simply proxying methods.

On one hand, it makes configurability via configuration far quicker but on the other hand, it makes for more of a maintainability nightmare - especially for future versions.  I would say customized handling such as this should be done manually.  But feel free to disagree :)

**Comment by stefanotorresi** [comment]
i think the problem is that right now there is no way to configure the `PlatesEngine` because it's not accessible anywhere, and the renderer factory always instantiate a new one rather than pulling one from the container.
so as it stands, the implementation is quite closed, and to customize the engine one would need to replace the whole renderer factory, which is odd.

**Comment by stormwild** [comment]
> I would say customized handling such as this should be done manually. 

I understand, I was hoping it would have been good to have it enabled for the skeleton by default.

**Comment by weierophinney** [comment]
While I get the objections that @mwillbanks raises, the fact is that
"asset" helpers are already enabled by default in both the twig and
zend-view implementations. As such, we likely should enable them for
plates.

I see two ways to do so:
- add functionality to the factory for registering them; we have this in
  both the other implementations already (extensions in twig, helpers for
  zend-view).
- allow pulling the base plates engine instance via a factory (which would
  allow configuring it in an application-specific factory)

Anybody want to start a pull request?
